align the docs with Docker's style guide and other documentation
docker/extensions-sdk pull request #141
Opened 2022-04-28 12:57 UTC by aevesdocker

2022-04-29 17:10 UTC, benja-M-1 requested changes
Amazing work @aevesdocker thank you very much for that! 

I made some comments when I found extra space or extra `the` :)
I found some places where the `make extension` command is mentioned and it should be replaced by `make build-extension`. Do you want me to push a commit on the PR or are you ok to do the change?

@gtardif in the tutorials we repeat every time how to build, validate, push, publish, etc. In another PR, can we extract this and include it where needed? 
Otherwise, I suggest we revisit a bit how tutorials are organized. For example, we could have a page per step and link to the validate/build/push/publish page at the end.

2022-05-02 09:22 UTC, gtardif approved these changes

2022-05-02 09:27 UTC, benja-M-1 approved these changes

2022-05-02 09:43 UTC, merged

2025-09-05 16:05 UTC, Amnat-auyana1998 approved these changes