Updated design guidelines
docker/extensions-sdk pull request #155
Opened 2022-05-06 16:44 UTC by mel-manohar

The design section in docs will now has 3 subsections: UI Kit, Guidelines, Docker's Design Principles

2022-05-09 10:05 UTC, benja-M-1 requested changes
@mel-manohar I think you can get rid of the `<br>` and just add a carriage return instead. The markdown parser should replace them with a `<br/>` itself.

2022-05-09 10:05 UTC, benja-M-1 commented on docs/design/design-guidelines.md
> +
nit: we can remove those lines

2022-05-09 10:19 UTC, mel-manohar commented on docs/design/design-guidelines.md
> +
Removed

2022-05-09 10:21 UTC, mel-manohar commented
@benja-M-1 when I preview it in (VSCode) without the <br> tags, the carriage return does not seem to automatically include the line break. Should I still remove it ?

2022-05-09 12:43 UTC, mel-manohar commented
> Do you mean the content all appears on one line, or that there isn't enough space between the lines (so you wanted a blank one to pad it out further). If the former, something weird is happening. If the latter, we should defer to the docs site's stylesheet (which VS Code's preview won't reflect).

It was the latter. I have removed the <br> now.

2022-05-09 12:43 UTC, closed without merging

2022-05-09 14:07 UTC, mark-dr commented
Was this deliberately closed, @mel-manohar? My PR (#158) was based on it :sweat_smile:

2022-05-09 14:09 UTC, mel-manohar commented
@mark-dr by mistake sorry Mark. I meant to simply comment. Re-opened now.

2022-05-09 15:28 UTC, aevesdocker approved these changes
Some nit-picky tweaks @mel-manohar

2022-05-09 15:28 UTC, aevesdocker commented on docs/design/design-guidelines.md
> +- Ensure the extension has both a light and dark theme. Using the components and styles as per the Docker styleguide will ensure that your extension meets the [level AA accessibility standard.](https
```suggestion
- Ensure the extension has both a light and dark theme. Using the components and styles as per the Docker style guide ensures that your extension meets the [level AA accessibility standard.](https://www.w3.org/WAI/WCAG2AA-Conformance)
```

2022-05-09 15:28 UTC, aevesdocker commented on docs/design/ui-kit.md
> +Our Design System is currently being developed. In the meantime, you will find some basic styles (color, typography) and components in this [Docker Extensions Styleguide](https://www.figma.com/file/U
```suggestion
Our Design System is currently being developed. In the meantime, you will find some basic styles (color, typography) and components in this [Docker Extensions Styleguide](https://www.figma.com/file/U7pLWfEf6IQKUHLhdateBI/Docker-Design-Guidelines?node-id=1%3A28771). Using the components and styles as per the Docker Extensions Styleguide, ensures your extension meets the [level AA accessibility standard.](https://www.w3.org/WAI/WCAG2AA-Conformance)
```

2022-05-09 16:41 UTC, mel-manohar commented
Thank you so much @aevesdocker

2022-05-10 07:04 UTC, benja-M-1 requested changes
@mel-manohar I add more `<br>` removals :) After that it should be good :+1:

2022-05-10 07:04 UTC, benja-M-1 commented on docs/design/ui-kit.md
> +<br>
```suggestion
```

2022-05-10 07:04 UTC, benja-M-1 commented on docs/design/design-principles.md
> +<br>
```suggestion
```

2022-05-10 07:04 UTC, benja-M-1 commented on docs/design/design-principles.md
> +<br>
```suggestion
```

2022-05-10 07:04 UTC, benja-M-1 commented on docs/design/design-principles.md
> +<br>
```suggestion
```

2022-05-10 07:04 UTC, benja-M-1 commented on docs/design/design-principles.md
> +<br>
```suggestion
```

2022-05-10 07:04 UTC, benja-M-1 commented on docs/design/design-principles.md
> +<br>
```suggestion
```

2022-05-10 10:02 UTC, gtardif approved these changes

2022-05-10 10:04 UTC, gtardif commented
Fixed image links / size after jekyll docs generation (for docs.docker.com)

<img width="1091" alt="Screenshot 2022-05-10 at 12 03 30" src="https://user-images.githubusercontent.com/437958/167604047-fd7e710b-8c99-4a2a-bdf6-663f567d5a9e.png">